### PR TITLE
Don't use Nagios embedded Perl interpreter.

### PR DESCRIPTION
**Pull request by sebastic**
ePN has issues with the VMware Perl SDK.

### CODE REVIEW

**Comment by chelmertz** [comment]
Hi again @sebastic , thanks for the PRs!

Sorry, but I'm taking on the boring-gatekeeper role:

- Which steps can I take to reproduce your issue?
- What was supposed to happen?
- What did happen?

**Comment by sebastic** [comment]
Steps to reproduce:
 * Configure a service check to use {{check_vmware_api.pl}} in Icinga (1.x on Debian stable)

What was supported to happen?
 * Check command completes successfully in a sort time

What did happen?
 * VMware Perl SDK modules could not be loaded by ePN

**Comment by sebastic** [comment]
See also [[op5-users] esxi check speed](http://lists.op5.com/pipermail/op5-users/2011-October/012283.html) for a similar issue.

In my experience only simple check plugins benefit from ePN.

**Comment by jacobbaungard** [comment]
This plugin is "deprecated" from our side, and so most likely won't see any updates. We are therefore closing all open PRs. Sorry about that.

The following project, which was forked from this one, might be of interest to you: https://github.com/BaldMansMojo/check_vmware_esx/

**Pull request closed without merging**
